name: Pull GitHub Repository Contents and Deploy to Jenkins

on:
  push:
    branches: [main]

jobs:
  pull_repo_and_deploy:
    name: Pull GitHub Repository Contents and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.YUSUFME3 }}
          password: ${{ secrets.YUSUFME3P }}
          repository: yusufme3/yr-apache-image
          tag_with_ref: true

      - name: Create SSH directory for the second instance
        run: mkdir -p ~/.ssh

      - name: Write private key to file for the second instance
        run: echo "${{ secrets.YUSUFKEY }}" > ~/.ssh/RHY.pem

      - name: Set permissions for private key file for the second instance
        run: chmod 600 ~/.ssh/RHY.pem

      - name: Update known_hosts file for the second instance
        run: ssh-keyscan -H 3.72.74.84 >> ~/.ssh/known_hosts

      - name: SSH into the second instance
        run: ssh -i ~/.ssh/RHY.pem ubuntu@3.72.74.84

      - name: Stop and remove Apache Docker container
        run: |
          docker stop apache || true
          docker rm apache || true

      - name: Trigger Jenkins Pipeline
        run: |
          curl -X POST \
            -u YusufRiyad:111e297342cff6b975e53e2c71e1a79f59 \
            -d '' \
            http://3.75.180.85:8080/job/RY/build
