name: Pull GitHub Repository Contents and Deploy to Jenkins

on:
  push:
    branches: [main]

jobs:
  pull_repo:
    name: Pull GitHub Repository Contents
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create SSH directory
        run: mkdir -p ~/.ssh

      - name: Write private key to file
        run: echo "${{ secrets.YUSUFKEY }}" > ~/.ssh/RHY.pem

      - name: Set permissions for private key file
        run: chmod 600 ~/.ssh/RHY.pem

      - name: Update known_hosts file
        run: ssh-keyscan -H 3.75.180.85 >> ~/.ssh/known_hosts

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.YUSUFME3 }}
          password: ${{ secrets.YUSUFME3P }}

      - name: Build Docker image
        run: docker build -t yusufme3/yr-apache-image:latest .

      - name: Push Docker image
        run: docker push yusufme3/yr-apache-image:latest

      - name: Trigger Jenkins Pipeline
        run: |
          curl -X POST \
            -u YusufRiyad:111e297342cff6b975e53e2c71e1a79f59 \
            -d '' \
            http://3.75.180.85:8080/job/RY/build
