name: Trigger Jenkins Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Jenkins
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Jenkins Pipeline
        run: |
          curl -X POST \
            -u YusufRiyad:111e297342cff6b975e53e2c71e1a79f59 \
            -d '' \
            http://3.72.38.22:8080/job/RY/build
